### ISSUE TITLE
Newly added segments should have terminology populated

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#104]
It is highly non-intuitive that newly added segments have no terminology at all.

![image](https://cloud.githubusercontent.com/assets/313942/20575272/98624a36-b186-11e6-97e4-0c4a986c2146.png)

@che85 can we assign Tissue/Tissue in a new segment event handler? We went over this several times to change the default behavior in Segment Editor proper, and never reached consensus.

As it is right now, the user needs to assign terminology manually before being able to export. My goal is to make user minimally aware of either terminology or DICOM, and not to introduce extra work.

Also, let's change the column name from "Color" to "Terminology", and assign segment name to be `<segmentation property type>_<segment number>` - I think this is more intuitive than `Segment_<segment number>`.

These are nice to have, but not critical for RSNA. Let me continue with the review of #102 and after I am done we will prioritize.

**Comment by pieper** [comment]
Wouldn't the column name be "Term" instead of "Terminology"?

**Comment by fedorov** [comment]
@pieper  -- agreed!

**Comment by lassoan** [comment]
Renaming Color to Terminology would be confusing. Maybe we should bring up the terminology window when segmentation name column is double-clicked. It would be better if double-clicking on color swatch would bring up a simple color selector anyway (now you need to do too many clicks to simply change color).

**Comment by fedorov** [comment]
@pieper - maybe it should be even more specific - maybe "semantics" is appropriate in this context?

**Comment by fedorov** [comment]
@lassoan - why would it be confusing? I think it is more confusing when user only sees color, and has no idea that that color square is hiding more than just the color. To clarify, I am not pushing for a change in Segment Editor (although, it would be appropriate too), but only in this Reporting module.

**Comment by che85** [comment]
I totally agree, but I also think that user just might not know about the fact that he/she is actually able to change the terminology by dblclicking onto the color. 

We shall find a better way for making that more visible more intuitive to the user.

**Comment by fedorov** [comment]
@lassoan I also agree that changing color independently is a good feature. Maybe we should have separate column for color, and separate column/button for defining the semantics of the segment. That would be fine with me. All I am saying the current UI is sub-optimal. 

But we DO have a functional Beta, and all of the team contributed a lot to make it happen. Thank you all for the hard work!!!

**Comment by lassoan** [comment]
We all agree then: Associating color with terminology is confusing.
Renaming column would be confusing because colors are very weakly linked to terminology and we would still just show colors in that column.

Assigning terminology editing to double-clicking in color column is confusing because:
1. user just sees the color and wants to change the color and instead of a color selector he is presented with a complex dialog box.
2. You can change segment name too easily to "liver" while leaving terminology as tissue/tissue
3. user double-clicks to change color and may end up changing segment name (different column

Double-click on segment name is not obvious either but less confusing.

We could bring up the terminology window for double-clocking both columns to make it a bit more difficult to change colors without seeing associated terminology - but I don't think that this restriction is needed.

**Comment by fedorov** [comment]
Right, but there are different levels of association.

One (which we all agree is confusing and should be improved) is the association in the user interface.

Second one is the assignment of the default suggested color in the segmentation terminology context. I believe that one should stay, and terminology popup widget should keep the color swatch. But there should be an additional color swatch to allow the change of the color assigned by default.

> We could bring up the terminology window for double-clocking both columns to make it a bit more difficult to change colors without seeing associated terminology - but I don't think that this restriction is needed.

I would prefer having a separate column/button for setting terminology on a per-segment basis. I don't like hidden functionality, at least not in this case. Segment name should be editable independently of the term, since it is a free-text entry and user should be able to change the default suggested value.

**Comment by fedorov** [comment]
@che85 as an intermediate solution, can you please implement the following:

 - [ ] assign tissue/tissue terminology codes at the time new segment is created (right now it is "blank"/"blank"), and pop up the Terminology selection dialog pre-populated so user can modify the selection
 - [ ] assign new segment name to be  `<SegmentationCategoryType>_<number>`, where `number` is `<number of segments with the segment name starting with SegmentationCategoryType>+1`

**Comment by lassoan** [comment]
> pop up the Terminology selection dialog

For some use cases it's important to force the user to tell in advance what that segment will contain => showing a modal popup is a good choice.

Other times the user just wants to try something or create temporary segments that may not even have physical meaning (e.g., a mask to temporarily constrain painting in a certain region) => allowing the user to create new segment with a single click is a good choice.

There could be a flag in the Segment Editor widget that controls this behavior (ShowTerminologyPopupOnAddSegment or something similar).

**Comment by che85** [comment]
I agree, we could always just open that dialog once a segment is added with preselected category Tissue and type Tissue. That would be one more click.

I can also imagine to have a checkbox within the terminology widget next to the buttons which says "set as default" for preventing the dialog to popup every time a segment is added. You could save that default in Slicer settings or just leave it temporary as long as the current Slicer session is running.

**Comment by cpinter** [comment]
Change committed in
https://github.com/Slicer/Slicer/commit/00f4d75d9695a97d5926fe073c48077449130829

**Comment by cpinter** [comment]
@fedorov Have you been able to test it in the nightly? Please let me know if there are issues. Otherwise this can be closed. Thanks!

**Comment by fedorov** [comment]
I am just in the process of doing it. We ran into some issues (non-applicable attributes are stored into JSON with the value of `null`), which I think might be related to the changes in the core, but we can handle them on our side. I think the main issue is resolved, so I am going to close this.

**Comment by che85** [comment]
Yes I am going to fix that issue on our side. Thanks a lot for the changes @cpinter it looks great.

**Comment by cpinter** [comment]
Thanks Andrey and Christian! If the Json issue is something that can be addressed in the core, then I'd be happy to do that (it's best to fix bugs where they originate).

**Comment by che85** [comment]
To me it makes sense to set it to null on your side, I just need to check if it's null. That's all.

**Comment by fedorov** [comment]
Definitely, Christian is investigating it, he will let you know if it is supposed to be fixed in the core.

Indeed, things look great, thank you for working on it!
