### ISSUE TITLE
LoadAnatomicContextFromSegmentDescriptorFile fails when no anatomic region is present

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#118]
@cpinter this call locks up Slicer https://github.com/QIICR/Reporting/blob/master/Py/DICOMSegmentationPlugin.py#L167

Test dataset is attached. 
[liver.dcm.zip](https://github.com/QIICR/Reporting/files/613845/liver.dcm.zip)

this is happening with a SEG dataset that does not have anatomic region populated. As a workaround, we can skip calling this function when anatomic region is not present, but I think it should not lock Slicer application!

**Comment by fedorov** [comment]
Added "high priority" since the workaround is not that simple, and I don't know all of the consequences!

**Comment by cpinter** [comment]
Hm I thought I implemented it in a way that it would't fail. Didn't test it though. I'll fix this asap

**Comment by cpinter** [comment]
Fixed in Slicer core rev25576.
Sorry for the trouble! We'll need to add automatic tests to make sure there are no regressions.

**Comment by fedorov** [comment]
Great, thanks! I confirm it is working in my local build.
