### ISSUE TITLE
RSNA2016 bug list

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#120]
Let's keep adding here issues identified during the conference instead of creating a new issue each time. After RSNA we can triage and decide how to proceed.

- [x] the module does not work in Slicer installed from scratch, since developer mode is not enabled, and it cannot find widgets!
- [x] SR round-trip does not work if Slicer is restarted - somehow the DICOM files created by the SR converter are not available after restart (either temp dir is removed by the OS, or something else; probably the files created by the converters should be moved to the DICOM import directory)
- [x] when switching to 4up-table layout, the table in the layout is not responsive to the mouse clicks; perhaps this is intentional, but not intuitive
- [x] for SRs that reference RWVM, scaling should be applied (specifically in the PET/SUV scenario)

**Comment by lassoan** [comment]
"it cannot find widgets" => In general, only testing code should rely on finding widgets by Qt meta-object system, as these kind of lookups are invisible to developers and routine code changes may accidentally break them. It should be no problem to add the proper APIs to access all necessary widgets without searching.

**Comment by lassoan** [comment]
> switching to 4up-table layout, the table in the layout is not responsive to the mouse clicks; perhaps this is intentional, but not intuitive

Can you reproduce it by simply loading/creating table using Tables module and switching to 4up-table layout?

Table node supports locking to prevent accidental modifications. If a table is locked then you can still browse and copy the content but cannot modify it.

**Comment by fedorov** [comment]
> "it cannot find widgets" => In general, only testing code should rely on finding widgets by Qt meta-object system

I agree. Let's explore this. This approach is great for prototyping, but is not sustainable. Let's see how easy it will be to add all of the API calls to support this functionality properly.

> Can you reproduce it by simply loading/creating table using Tables module and switching to 4up-table layout?

Andras, I think this is related to how we customized table events for this module. What I asked Christian to implement is synchronized selection of rows in the table with the selection of segments in the segments list (this is the PR I believe: https://github.com/QIICR/QuantitativeReporting/pull/112/commits/98b2b85377b2dafc38cfab99f705b31093c896fb). But somehow the behavior is not the same when layout is changing. Maybe it changes the view in the 4up-table layout, and the event handler does not apply? @che85 what do you say?

**Comment by che85** [comment]
@fedorov I totally forgot about the 4up-table layout. Generally the module is only listening to click events but I should rather let it listen to selection changed events.

Regarding finding of widgets, I guess you only meant parts of the developer section, right? I am going to commit a fix for that.

@lassoan How do I directly access that table view?

**Comment by lassoan** [comment]
> How do I directly access that table view in the 4up-table layout?

slicer.app.layoutManager().tableWidget(0).tableView()

**Comment by fedorov** [comment]
Related to #116

**Comment by che85** [comment]
@fedorov I cannot reproduce the issues regarding the missing files after restarting Slicer SR round-trip. After creation of the SR and restarting Slicer, the DICOM Database doesn't have any issues finding the files.

**Comment by fedorov** [comment]
I can't reproduce it either. I tried today's nightly and cleanup_temp branch, and the only error I am getting is this:

![image](https://cloud.githubusercontent.com/assets/313942/21062988/60779228-be21-11e6-8006-60bb719fde87.png)
