### ISSUE TITLE
No quantity/units available for PET images while creating a measurement report

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#124]
@che85 Ron failed when trying to save a report for a PET series downloaded from TCIA - can you check?

**Comment by che85** [comment]
Which dataset? Or does it happen to all of them?

**Comment by che85** [comment]
Ok seems like identified issues when using one of the PET datasets

**Comment by che85** [comment]
Issues identified here:
https://github.com/QIICR/QuantitativeReporting/blob/b0576c8035f58ea0ce8d09fbe4d068b9136e03d4/Py/QuantitativeReporting.py#L1043-L1065

While creating measurement items for the structured report we are so far only providing quantity and units for CT and MRI images

**Comment by che85** [comment]
This issue is outdated and has been fixed recently (see https://github.com/QIICR/QuantitativeReporting/issues/129)
