### ISSUE TITLE
Store quantity and units of the loaded parametric map

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#127]
As discussed at project week and documented here http://wiki.na-mic.org/Wiki/index.php/2017_Winter_Project_Week/QuantitativeReporting, store the quantity/units as attributes of the loaded scalar volume.

**Comment by fedorov** [comment]
Same approach should be applied to other modalities/plugins.

* when Units attrubute is present, cross link
http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_84.html
and "C.8.9.1.1.3 Units" in
https://fedorov.cloudant.com/dicom_standard_2015c/.site/chtml/part03/sect_C.8.9.html
by code meaning
* MR: quantity: (DCM, 110852, MR signal intensity), units: (1, UCUM, "no units")
* PET: look at the Units attribute and follow the algorithm here: http://qibawiki.rsna.org/index.php/Standardized_Uptake_Value_(SUV)
* CT: quantity: (122713, DCM, "Attenuation Coefficient"), units ([hnsf'U], UCUM, "Hounsfield unit")

**Comment by che85** [comment]
@fedorov I think this issue has been resolved as well, right?

**Comment by fedorov** [comment]
yes
