### ISSUE TITLE
Add handling of quantity/units to SegmentStatistics

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#129]
Andras, can you add a feature to Segment Statistics to check for the presence of `DICOM.QuantityValueCode` and `DICOM.MeasurementUnitsCode` attributes at the input scalar volume, and if those are present, populate these attributes for the output created by SegmentStatistics?

**Comment by lassoan** [comment]
OK! Could you add a link to a scene file that contains such data?

**Comment by lassoan** [comment]
How would you like to see the units in the SegmentStatistics output on the GUI?
How would you like to save the output to file (additional rows or columns in the table csv; separate column metadata csv, ...)?

**Comment by fedorov** [comment]
> Could you add a link to a scene file that contains such data?

Attached.  [2017-01-24-Scene.mrml.zip](https://github.com/QIICR/QuantitativeReporting/files/727584/2017-01-24-Scene.mrml.zip) To reproduce, install QuantitativeReporting extension, and load this dataset: http://slicer.kitware.com/midas3/item/257243

> How would you like to see the units in the SegmentStatistics output on the GUI?

I am open to discussion/suggestions, but my initial thought was to use quantity code meaning in place of "GS" in the column names. See the discussion about suggested approach in https://github.com/QIICR/QuantitativeReporting/issues/105

>  How would you like to save the output to file (additional rows or columns in the table csv; separate column metadata csv, ...)?

I tend to prefer two csv files with separate file for column metadata.

**Comment by fedorov** [comment]
@lassoan do you need any more clarifications on this? What are the next steps and timeline?

**Comment by fedorov** [comment]
@lassoan when can I expect progress on this issue?

**Comment by lassoan** [comment]
I'm making progress but keep sidetracked by smaller or urgent tasks. I'll allocate more time for this and send updates more frequently.

**Comment by fedorov** [comment]
Andras, it would be great to have some kind of estimate of when you expect this issue to be addressed. Among other things, it is in the critical path for @chribaue work.

**Comment by fedorov** [comment]
Andras, as I was reviewing your update, I realized one thing got lost in dispersed discussions over various issues. The way measurements are encoded in DICOM is often by using post-coordinated approach. I thought I discussed this with you, but I cannot find it in issues, so maybe it was just a discussion at the project week.

Let's follow this example https://github.com/QIICR/dcmqi/blob/master/data/sr-example/sr.dcm (it is a dataset encoding measurements for the Iowa use case). The DICOM template corresponding to this section is [TID 1419](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_1419).

Here is the human-readable part with the measurements (output of dsrdump, as shown in Atom using [dicom-dump](https://atom.io/packages/dicom-dump) package).

![image](https://cloud.githubusercontent.com/assets/313942/26384827/bf4a58de-4009-11e7-8531-8dd4ba82d790.png)

Every measurement is encoded as a combination of 2 codes: quantity being measured (code 1) 
post-coordinated with the measurement type (code 2). In this case, "SUVbw" is the quantity, and measurement type ("Derivation") is "Mean", "Minimum", etc.

An alternative of this approach would be to have pre-coordinated codes, i.e., something like "SUVbw Mean", "SUVbw Minimum", etc, but this would require a lot more codes. With post-coordinated approach, concept can be "Attenuation", or "SUV", or "ADC", and the same set of post-coordinated derivation codes can be reused. Does it make sense?

I think for the table view headers, we can only use the derivation code meaning. As all segmentations/measurements will be done for the same volume, there is no need to duplicate this.

I hope this makes sense. We can discuss on Thursday, or I am also happy to chat earlier on Wed if needed. Sorry for not putting this in writing earlier, it is my fault.

**Comment by fedorov** [comment]
Here is one measurement from the example above at the level of individual DICOM attributes, for completeness.

![image](https://cloud.githubusercontent.com/assets/313942/26385380/3f5e6562-400d-11e7-85f4-ef1ecec99388.png)

**Comment by lassoan** [comment]
Yes, I know that we talked about this and the table properties infrastructure is ready to handle this, as any number of table column properties can be defined. I've added some convenience functions for setting units but it's easy to change them or add more as needed. It's also easy to change formatting of the tooltip text.

As a next step, it would be great if you could provide the followings:
* example schema file that contains all kinds of column properties you will need
* specify how would you like to show those properties in Slicer's table view
* specify what convenience functions you would like to have for getting/setting units, measurements, concepts, etc.

**Comment by chribaue** [comment]
Here's a table that lists all the quantities and units that we need for the PET scan measurements:

https://github.com/QIICR/Iowa2DICOM/blob/master/Resources/QuantitiesAndUnits.csv

This table assumes that the PET scan was normalized to SUVbw, but I want to support all SUV types that are supported by our Slicer PET DICOM extension; i.e. SUVbw, SUVlbm, SUVbsa, and SUVibw.

**Comment by fedorov** [comment]
> example schema file that contains all kinds of column properties you will need

The way measurements are currently communicated to and from the dcmqi converter are defined by this portion of the schema: https://github.com/QIICR/dcmqi/blob/master/doc/schemas/sr-tid1500-schema.json#L9-L21

To be sure future needs of communicating measurements using DICOM can be addressed easier, it will be good to support the other attributes that are in [TID1419](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_1419). Specifically, I think the following are relevant:
* arbitrary number of measurement modifiers (line 6 of the template). If my understanding is correct, these can, for example, be used to indicate that the image was smoothed before computing the quantity. Each modifier contains the code for the concept defining the modifier, and (I think!) code for the modifier value
* setter for the code for MeasurementMethod concept (line 7)
* arbitrary number of Derivation parameters (line 13) - each derivation parameter is defined by the number value, coded concept for the derivation parameter, and units (these can for example be used to communicate some relevant computation parameters)

I think the other lines are not immediately practical. I will put a note to also discuss this with @dclunie at our regular QIICR call tomorrow (if you like, you are welcome to join Andras, it is at 10am Eastern over hangout).

> specify how would you like to show those properties in Slicer's table view

I think those extra parameters that I listed do not need to show in the table. In https://github.com/QIICR/QuantitativeReporting/issues/105#issue-191366810 I suggested a strategy how we could initialize headers, given the attributes recovered from DICOM:
* when only quantity is available, show code meaning for quantity
* when quantity and derivation both are available, show code meaning for derivation
* when code meaning exceeds some length threshold, abbreviate to that length threshold
* always show quantity + derivation (when available) + units in the tooltip for both the column header and the cell content

How about this? If this does not work for the general case, we should just implement this in QuantitativeReporting.

> specify what convenience functions you would like to have for getting/setting units, measurements, concepts, etc.

@che85 can you help with this?

**Comment by lassoan** [comment]
Thank you, it's useful.

- What "Derivation" column is used for?
- How should we display properties stored in this table in Slicer?
- In quantity columns we sometimes have actual quantities (Volume) but in many cases there are just modifiers (Mean, Minimum, Maximum, etc). How would you store Mean volume?
- There is no column that contains a user-friendly unit name ("Units meaning" is too verbose, "Units code" is not human-readable). How would you generate a simple label that could be displayed in reports?
- "Quantity encoding" seems to describe the content of the entire table (it would be the table name, not the name of a particular column). I guess "Quantity encoding" column stores the data table column names, so it should probably be something like "Measurement name" or "Measurement ID".

**Comment by chribaue** [comment]
> How should we display properties stored in this table in Slicer?

here's a screenshot of how we used to display the measurements table to the user in our current PET measurement extension:
https://www.slicer.org/w/images/thumb/8/8e/PET-IndiC_Screenshot5.png/700px-PET-IndiC_Screenshot5.png

> In quantity columns we sometimes have actual quantities (Volume) but in many cases there are just modifiers (Mean, Minimum, Maximum, etc). How would you store Mean volume?

Mean refers to mean "grayvalue". The way I understand the segment statistics is that the measurements are per segment, so there would never be a mean volume calculated over several segments.

> There is no column that contains a user-friendly unit name ("Units meaning" is too verbose, "Units code" is not human-readable). How would you generate a simple label that could be displayed in reports?

As the screenshot above shows, we used the Units code to display it to the user. That's as human-readable as it gets...

> "Quantity encoding" seems to describe the content of the entire table (it would be the table name, not the name of a particular column). I guess "Quantity encoding" column stores the data table column names, so it should probably be something like "Measurement name" or "Measurement ID".

Quantity encoding is basically the "key" from your current segment statistics module; like your "GS mean" is the "Mean" in our table. "GS volume mm3" and "LM volume mm3" is similar to our "volume" but we use "ml" as units.

> What "Derivation" column is used for?

Andrey, can you explain this?

**Comment by fedorov** [comment]
> What "Derivation" column is used for?

Ok, sorry - I guess my explanation above did not help ... 

Here is the strategy I propose:
* when only quantity is available, show code meaning for quantity
* when quantity and derivation both are available, show code meaning for derivation
* when code meaning exceeds some length threshold, abbreviate to that length threshold
* always show quantity + derivation (when available) + units in the tooltip for both the column header and the cell content

specific example of a DICOM encoding of a measurement:

```
      <contains NUM:(,,"SUVbw")="6.23131" ({SUVbw}g/ml,UCUM,"Standardized Uptake Value body weight")>
        <has concept mod CODE:(,,"Derivation")=(C2347976,UMLS,"RMS")>
```

From this example, attributes would be initialized as follows:
1. Value: 6.23
2. Quantity: code tuple with "SUVbw" as code meaning
3. Units: code tuple with "{SUVbw}g/ml" as code value
4. Derivation: (C2347976,UMLS,"RMS")

Following the strategy above, column header is set to "RMS", column header tooltip is set to "SUVbw RMS, Units: {SUVbw}g/ml. Same strategy will apply to the calculations over other series types:
* CT: Quantity: (122713, DCM, "Attenuation Coefficient"), units: (1, UCUM, "no units")
* MR: Quantity: (DCM, 110852, MR signal intensity), units: (1, UCUM, "no units")
* parametric maps: quantity and units are directly initialized from DICOM by the Parametric map plugin: https://github.com/QIICR/QuantitativeReporting/blob/master/DICOMPlugins/DICOMParametricMapPlugin.py#L121-L125
* PET initialized from the vendor-specific attributes http://qibawiki.rsna.org/index.php/Standardized_Uptake_Value_(SUV), or from the standard locations, including the various flavors of SUV corrections

Another example (no Derivation): 
```
<contains NUM:(,,"Glycolysis Within First Quarter of Intensity Range")="41.9512" (g,UCUM,"Gram")>
```

Column header is set to either "Glycolysis Within First Quarter of Intensity Range", abbreviate to a shortened version. The abbreviation should be done by the statistics plugin, and use as the header of the column. 

> How should we display properties stored in this table in Slicer?

See the strategy I suggested earlier. We don't need to display all of the properties in Slicer UI. I don't see the need for that. Perhaps in tooltips, if you think it is needed?

> In quantity columns we sometimes have actual quantities (Volume) but in many cases there are just modifiers (Mean, Minimum, Maximum, etc). How would you store Mean volume?

I think in most cases the strategy I suggested will result in meaningful names, but I agree that it is impossible to anticipate all situations. Perhaps a plugin can define a function to query for the value to be displayed for individual measurements/column headers, if the default strategy is insufficient.

> There is no column that contains a user-friendly unit name ("Units meaning" is too verbose, "Units code" is not human-readable). How would you generate a simple label that could be displayed in reports?

I disagree, I think in most cases it is human readable. When it is not human readable, or not what one would expect, the plugin could define a lookup table perhaps?

> "Quantity encoding" seems to describe the content of the entire table (it would be the table name, not the name of a particular column). I guess "Quantity encoding" column stores the data table column names, so it should probably be something like "Measurement name" or "Measurement ID".

[This table](https://github.com/QIICR/Iowa2DICOM/blob/master/Resources/QuantitiesAndUnits.csv)  should not be used as a reference! It is just a temporary data structure used by the converter script for the conversion of the data in this paper: https://peerj.com/articles/2057/. It is not intended as an example or the recommended approach for displaying these items!

**Comment by chribaue** [comment]
Andrey, is this the correct table what extra DICOM related information the PET segment statistics plugin should return for its measurements?
https://dfzljdn9uc3pi.cloudfront.net/2016/2057/1/Appendix3SUVmeasurementscodes.pdf

**Comment by fedorov** [comment]
@chribaue the table is just a summary of the codes, I don't think the plugin should return exactly this table. But yes, it should contain the latest set of codes we used for encoding the data. I think if we follow our naming convention used in this discussion, the second would be called "Quantity", and we would take the items mentioned in the 4th column (modifier code) in the cases when modifier relationship is "Derivation".

**Comment by fedorov** [comment]
As pointed out by @dclunie, we can use line 18 of http://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_A.html#sect_TID_1419 ( (121050, DCM, "Equivalent Meaning of Concept Name")) to store the alternative name describing the measurement. This can be combining quantity and derivation meanings, for example.

**Comment by lassoan** [comment]
Table properties feature is now merged into the trunk.

Currently the only special properties are longName, description, and unitLabel - these are displayed in the tooltip. For now, if you want to display anything to the user then you can write that in these properties. We can change this quite easily if we find that this is not good enough.

**Comment by che85** [comment]
I think this issue has been resolved. If I am right, let's close it.
