### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#130]
@che85 can you please add some documentation for the module?

I think doing it using gitbook following the template of SliceTracker is the most practical option, what do you think?

Also note that recently gitbook added capability to publish multiple files at once, so we might consider keeping documentation in the master branch instead of keeping a separate branch.

**Comment by che85** [comment]
Sure I can do that.

**Comment by che85** [comment]
The thing with having it in the master branch that we will have a lot more commits, which I don't really like. In my opinion there should be a clean separation between code and documentation

**Comment by fedorov** [comment]
I think with the new gitbook features, it is less and might be more manageable, but I agree it might be better to keep them separately. Looking at the commit history for the dcmqi gitbook branch, it can get very messy! https://github.com/QIICR/dcmqi/commits/gitbook

**Comment by che85** [comment]
- [ ] add link to documentation
