### ISSUE TITLE
Failure when selecting parametric map as input for annotation

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#131]
Not sure what is going on ...

![image](https://cloud.githubusercontent.com/assets/313942/22260906/eefa40dc-e238-11e6-9097-0db9bc72d0f3.png)

Test dataset: http://slicer.kitware.com/midas3/item/257243

**Comment by che85** [comment]
Not reproducible on my machine. The only thing, that I noticed is the usage of logging where logging is not imported in DICOMParametricMapPlugin.py

**Comment by fedorov** [comment]
did you test with today's nightly?

I thought I added import logging, will check...

**Comment by che85** [comment]
No it's an older one. I will download today's ...

**Comment by che85** [comment]
Right, you added logging.

**Comment by che85** [comment]
@fedorov Importing it from DICOM and loading it into Slicer works without problems on my machine. Am I missing some steps?

**Comment by fedorov** [comment]
What happens when you set it as input in QuantitativeReporting?

**Comment by che85** [comment]
That works for me too. The only thing that doesn't work is saving a SR for this series, since there are information missing in the reference image.

**Comment by fedorov** [comment]
The issue appears to be unrelated to this module, is not always reproducible, and does not affect operation of the module (export is not supported for this specific type of data, but that is being handled in other issues).
