### ISSUE TITLE
DICOM export plugin

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#140]
Currently it is only possible to export segments that were created within QuantitativeReporting. Need to investigate the generic DICOM export plugin mechanism to make this more broadly available. The challenge is that we will only be able to support export of segments done on a DICOM series.

TODO:
 - [x] test Subject Hierarchy 2.0 and look into how DICOM export plugins are supported there

**Comment by fedorov** [comment]
TODO: 

 - test Subject Hierarchy 2.0 and look into how DICOM export plugins are supported there

**Comment by cpinter** [comment]
The DICOM plugins work exactly the same way, but instead of storing subject hierarchy nodes, it stores subject hierarchy item IDs (and the getter functions etc are different). So if you check it out in the current Slicer code, the idea will be the same, and the code will be very similar.

The only thing I suggest is to wait for the new one before making any changes.

**Comment by cpinter** [comment]
I came across SEG export, and I see it hasn't been updated yet. @fedorov do you want me to get started on porting it to SH2?

**Comment by fedorov** [comment]
@cpinter yes this would be great!

**Comment by cpinter** [comment]
I'm almost done, but there is one missing component, which is the CLI that does the export. It was called encodeSeg, and it was included in Reporting, but I cannot find it now. Can you please help me finding it?

**Comment by fedorov** [comment]
@cpinter the converter CLI is now provided by the DCMQI extension, it is documented here: https://qiicr.gitbooks.io/dcmqi-guide/user_guide/itkimage2segimage.html, and example usage from Slicer is here: https://github.com/QIICR/QuantitativeReporting/blob/master/QuantitativeReporting.py#L501.

@che85 can you please work with Csaba to help him integrate the converter and pass all metadata properly? Please let me know when you think it is ready so I can review before it is merged!

**Comment by cpinter** [comment]
Thanks, Andrey!

Probably it would make sense to create the PR now, because I'm at the point where SH2 and Terminologies are properly used, and the terminology triplet strings are created, and it's just the last few lines of the function that doesn't work, which is the one that calls the CLI.

Having written this down, it seems that this export plugin weren't updated several times when changes happened in the core and in DCMQI/QuantitativeReporting, each of which would have broken it itself. I think an automated test would be very useful!

**Comment by che85** [comment]
I will take a look and submit a PR to @cpinter

**Comment by che85** [comment]
@cpinter Going to wait for SegmentStatistics integration into Slicer Core and Quantitative Reporting before I will continue with this issue.

**Comment by cpinter** [comment]
I tested the exporter, and I found two issues:
* The exporter does not take the selected folder into account. 1. User selects folder to export the files to, 2. Clicks Export, 3. Popup appears saying that the files have been successfully exported the files (and includes the selected path), 4. Folder is empty, the file is in the Temp directory. I think this should definitely be fixed. The exportable contains the directory so it should not be a big task.
* There are memory leaks:
Class "vtkCellData" has 4 instances still around.
Class "vtkPointData" has 4 instances still around.
Class "vtkPoints" has 4 instances still around.
Class "vtkInformation" has 4 instances still around.
Class "class vtkBuffer<short>" has 4 instances still around.
Class "vtkInformationIntegerPointerValue" has 4 instances still around.
Class "vtkOrientedImageData" has 4 instances still around.
Class "vtkIdList" has 4 instances still around.
Class "vtkDoubleArray" has 4 instances still around.
Class "vtkInformationIntegerValue" has 16 instances still around.
Class "vtkShortArray" has 4 instances still around.
Class "vtkVoxel" has 4 instances still around.
Class "vtkFieldData" has 4 instances still around.
Class "class vtkBuffer<double>" has 4 instances still around.
Class "vtkCommand or subclass" has 6 instances still around.
Class "class vtkShortArray" has 4 instances still around.
Class "class vtkVoxel" has 4 instances still around.
Class "class vtkFieldData" has 4 instances still around.
Class "class vtkCommand" has 4 instances still around.

**Comment by che85** [comment]
@cpinter Good point. I just noticed the same. 

About the memory: Do you think that's caused by the exporter? I am not sure but I don't think so.

**Comment by cpinter** [comment]
What I did when getting the leak was 1. Load CT, 2. Segment Editor, 3. Export, 4. Import. I'll do a more detailed experiment and report back.

**Comment by cpinter** [comment]
You're right, the exporter does not leak. It was step 4: Loading the DICOM SEG back to Slicer that caused the leak.

I noticed something else now. Even if the Import exported data chackbox is not checked, the exported SEG is imported. Is it done by the exporter plugin? If yes, then it can be removed, as the export mechanism does the import if the user check the checkbox. If no, then I need to look into the export mechanism.
