### ISSUE TITLE
Layout optimization to minimize empty space (e.g., Effects panel has a big empty area)

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#144]

**Comment by cpinter** [comment]
As far as I know @lassoan took this task, please assign to him

**Comment by lassoan** [comment]
Please check the layout in latest nightly version, there is no more wasted space. I've found it difficult to find and click effect buttons, especially on high-DPI screens so I've made the effect name appear by default but it can be switched off if you are tight on space.

**Comment by che85** [comment]
@lassoan why would you display `Options` even when there are no options available?
![image](https://cloud.githubusercontent.com/assets/10195822/23481733/8228c93c-fe9a-11e6-94b8-4ea46b98d1c3.png)


## And still even if there are options available it takes more space than it should.

![image](https://cloud.githubusercontent.com/assets/10195822/23481785/b9e46098-fe9a-11e6-9310-b4aeba54a757.png)

**Comment by cpinter** [comment]
Probably getting the size hint from the options widget and setting its height to its container would solve it.
Also we could do this for the segment list too (and maximize its size in N segments). Thoughts?

**Comment by che85** [comment]
I am going to close this issue. Saving space has improved a lot.
