### ISSUE TITLE
Make list of displayed effects configurable

### ISSUE THREAD

**Issue by lassoan** [QIICR/QuantitativeReporting#147]
For example: setAvailableEffects([Paint, Draw, Erase, ...])

**Comment by lassoan** [comment]
Implementation is ready (https://github.com/Slicer/Slicer/commit/abd8faf149fe6de0df4a63fec5c03d98e74312dd), will be available in tomorrow's nightly. Please test and reopen the ticket if there is any problem or need for enhancement.

**Comment by fedorov** [comment]
@che85 can you please test and comment here?

**Comment by che85** [comment]
That works fine. Thanks!
