### ISSUE TITLE
Add selector for Anatomic context

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#150]
Now that there are multiple types of input JSONs, it will probably be good to check the `@schema` attribute in the input files to confirm what they represent.

https://github.com/QIICR/dcmqi/blob/master/doc/segContexts/AnatomicRegionAndModifier-DICOM-Master.json#L3

**Comment by fedorov** [comment]
cc: @chribaue

**Comment by cpinter** [comment]
The schema attribute is not present in the json files in Slicer core.
https://github.com/cpinter/Slicer/blob/master/Modules/Loadable/Terminologies/Resources/AnatomicRegionModifier-Master.json
Shouldn't they be updated?

**Comment by fedorov** [comment]
Let's wait for a little bit more. The updated version of AnatomicContext is missing `showAnatomy` attribute (@dclunie is working on fixing that). 

Also note that @chribaue reported a crash trying to load AnatomicContext with the current implementation. I guess once we have the schema attribute initialized, you would be able to check that and ignore json files that are not relevant, right?

**Comment by cpinter** [comment]
Also, how much should we rely on these attributes? What I mean is that currently there is one user directory for terminologies, and
1. If we consider these attributes mandatory and that they unambiguously identify whether the file is a terminology or anatomic context, then we can put them in that directory
2. But if we cannot rely on the attribute in the above way, then we could create another AnatomicContexts directory alongside the Terminologies one under the same NA-MIC folder

**Comment by fedorov** [comment]
We control those files, ideally they should be mirrored from dcmqi, so I think it should be ok to rely on the presence of the schema attribute. This would also force the users creating their own contexts to validate the files before they try to load them in Slicer. We have an online tool for that: http://qiicr.org/dcmqi/#/validators

**Comment by fedorov** [comment]
> The updated version of AnatomicContext is missing `showAnatomy` attribute 

Sorry, I should correct myself - the updated version of the SegmentationContext is missing that attribute: https://github.com/QIICR/dcmqi/blob/master/doc/segContexts/SegmentationCategoryTypeModifier-DICOM-Master.json. So it should be safe to take the current version of AnatomicContext-DICOM, and also update the version of SegmentationContext-DICOM-Master from January, which has showAnatomy attribute: https://github.com/QIICR/dcmqi/blob/feb32639f7498fb6df59a78dfa17ce9d99f7dc32/doc/segContexts/SegmentationCategoryTypeModifier-DICOM-Master.json

**Comment by cpinter** [comment]
OK so the schema attribute can identify the type well in the files we control.

My question was intended to be about the files the users load, and are copied into a user folder (the above mentioned NA-MIC/Terminologies one), from where they are loaded at startup.
So if we expect the users to have this attribute there the correct way, then we can have the one folder. Otherwise, if we allow sloppyness, then we need another one :)

About your question three comments back, yes, it would be easy to check the json files and only load those that have the accepted schema attribute values, and automatically load them as the proper type (terminology vs anatomic context)

**Comment by cpinter** [comment]
I'll update the json files then. Is the SlicerGeneralAnatomy one from January also OK?

**Comment by fedorov** [comment]
> My question was intended to be about the files the users load, and are copied into a user folder

Right, I would encourage users to follow the schema and validate jsons before trying to import them.

Let me list the versions of JSON files that I believe are correct and should be used:

* DICOM Anatomic context - use master: https://github.com/QIICR/dcmqi/blob/master/doc/segContexts/AnatomicRegionAndModifier-DICOM-Master.json
* DICOM Segmentation context - use this version (I used a wrong URL in an earlier comment): https://github.com/QIICR/dcmqi/blob/4552bf12c175f05b5ea97ebc285101ae49ddf18e/doc/segContexts/SegmentationCategoryTypeModifier-DICOM-Master.json
* Slicer Segmentation context - use master: https://github.com/QIICR/dcmqi/blob/master/doc/segContexts/SegmentationCategoryTypeModifier-SlicerGeneralAnatomy.json

**Comment by cpinter** [comment]
Great, thanks!

**Comment by cpinter** [comment]
Commit made in https://github.com/Slicer/Slicer/commit/14e5b76d6dcc291ebaec7dcf53a45f5d5867f316
If is supposed to fix each request in this issue.

**Comment by fedorov** [comment]
Thank you!

@chribaue please let us know if this works for you, and please consider contributing the json files you created for your application to dcmqi.

**Comment by chribaue** [comment]
Thank you! I will test it with the next nightly build of Slicer.

**Comment by pieper** [comment]
I hope that by "encouraging users to follow the schema" you don't mean that
Slicer will crash when supplied invalid files!  I guess you mean that there
will be an error dialog that points them to the validation tool?

Did you try the validation tool with the current QWebView in Qt4?  I may
work.  if not it will surely work in Qt5's QWebEngine ore for now we could
also open their default browser to the site.  So we should think about just
brining the tool up pre-loaded with the invalid file so they can fix it or
author a new one directly.

**Comment by cpinter** [comment]
@pieper I added safeguards for missing/invalid schema. There is an error message box popping up, with the details in the log.

**Comment by fedorov** [comment]
@pieper by "encouraging users to follow the schema" I mean just that. No, I don't think we tried loading the validator in web view. @che85 can you try that? Definitely it would be ideal to be able to validate incoming JSON.

**Comment by che85** [comment]
Using the validators with QWebView works, but the layout is somehow messed up. I am not sure if this is related to the webview itself or to AngularJS

**Comment by cpinter** [comment]
Sounds good. Once @che85 investigated embedding the validator, I can make the popup dialog more specific, and add a shortcut to the validator.

**Comment by che85** [comment]
I tested on Google Chrome, Safari, Microsoft Edge and Firefox. All of them display the validator page correctly. 

So I assume that's related to the QWebView then.

**Comment by chribaue** [comment]
I just tested loading my anatomic context json file. It works as it should. Loading an erroneous json file also doesn't crash Slicer anymore.

**Comment by cpinter** [comment]
Another reason to look forward to Qt5. I can simply present an http link that opens in browser.

**Comment by chribaue** [comment]
Using the functionality for selecting segmentation type and anatomic region, I would have one additional feature request:

Whenever, I click in the Segmentation Module (or the Segment Editor) on "Add Segment" and then want to select the segmentation type and anatomic region, the dialog dialog box for selecting these properties doesn't remember the segmentation category and anatomic context I had previously selected. I think, once a user selects a specific context, he/she wants to continue working within this context.

My application for example: I have a "Segmentation Category and Type - Head and Neck Cancer" and "Anatomic codes - Head and Neck Cancer". Once the user selects this context and continues segmenting additional structures, the newly segmented structures will also be head and neck cancer related.
Instead the Dialog box switches back to the "3D Slicer General Anatomy list" and "DICOM master list" which makes the whole work flow for the user more cumbersome.

Would this be something easy to change?

**Comment by cpinter** [comment]
@chribaue Very valid point. I can make the change relatively easily.

**Comment by che85** [comment]
@cpinter this code opens the native webbrowser

```
import webbrowser
url = "http://qiicr.org/dcmqi/#/validators"
webbrowser.open(url,new=2)
```

**Comment by fedorov** [comment]
@chribaue if I were you, I would go even further and constrain the user to the specific segmentation/anatomic context that makes sense for your application, since you are developing a custom workflow for a very specific analysis task. Depending on how you envision the use of your module, those selectors can be either completely hidden, or at least be collapsed. @cpinter what do you think? Should the widget be updated to allow this kind of configuration?

**Comment by fedorov** [comment]
Regarding validator, the ideal situation would be to validate imported json without any popups, and then only if the error is detected, show the validator window to allow fixing identified issues. @che85 do you think something like this could be possible?

**Comment by che85** [comment]
@fedorov I can imagine that with qt5 yes. I don't know much about the new api, but I assume, that even "simulated" user interaction should be easy, so that We could simply set the validation input to the validators and having a flag that signalizes validation errors and then pops up. 

We should only need to see if that's becoming annoying to the users and if so, we could make it optional and just display validation errors discreet to the user like "validation errors detected - click **here** for more information"

**Comment by fedorov** [comment]
Makes sense. I suggest for now we only pop up the validator if there are errors loading the context (i.e., C++ loader fails for whatever reason).

**Comment by cpinter** [comment]
@fedorov Constraining the user to specific context may be useful. How do you imagine setting/removing that constraint?

But in any case, I'd move that discussion to a different issue, as its scope is much larger than the simple default selection fix @chribaue suggested. I think I'll implement that for now though.

**Comment by cpinter** [comment]
@che85 Thanks but all of the terminologies logic and widgets are in C++

**Comment by fedorov** [comment]
> Constraining the user to specific context may be useful. How do you imagine setting/removing that constraint?

I would imaging to provide some API to hide those components for the developers integrating SegmentEditor into their workflows. It could also be helpful to put those selectors in a collapsible area, which would be open or closed depending on the developer preference.

> I'd move that discussion to a different issue, as its scope is much larger than the simple default selection fix

👍

**Comment by cpinter** [comment]
I started working on the navigator widget remembering the last context selection, but unfortunately it goes against a previous decision we made, namely that each new segment is assigned Tissue/Tissue, which entry is contained by the slicer general anatomy context.

@fedorov @lassoan What do you think should be the new behavior? A few options:
1. Set no terminology by default, and remember the last context selection, which is shown automatically when the terminology selector pops up for a new segment. (We could select category too if it helps more)
2. Set Tissue/Tissue by default, but if that default is detected, then show the last selection (same as 1)
3. ?

**Comment by fedorov** [comment]
Makes sense ... Another idea is to pre-select the first entry in the list of the selected context as default, when the first segment is added, and otherwise use the selection used for the last segment added?

**Comment by pieper** [comment]
How about adding a 'recently used' area in the widget, something like what
the color selector in the old editor did.

**Comment by cpinter** [comment]
@pieper This feature is in the plans, a.k.a "quick lists" or "presets". Now the question is simply the default selection for a new segment.

@fedorov "in the list of the selected context as default" - selected when?

**Comment by fedorov** [comment]
@cpinter isn't context an attribute for the segmentation created in SegmentEditor? Or is it completely separate and is only relevant in the terminology widget? I assumed Segmentation node is "parameterized" by segmentation and anatomic context.

**Comment by cpinter** [comment]
Terminology information is stored in the segments (contained by the segmentation, and the segmentation itself contains no terminology info). By default, a new segment's terminology tag is set to slicerGeneric/Tissue/Tissue. When the user invokes the terminology selector, the tag from the segment is read, and that entry is selected in the widget

**Comment by cpinter** [comment]
Personally, I'd go with suggestion 1, and in case of an empty terminology (which will be empty for new segmentations), the following will be pre-selected in the widget: terminology context, terminology category, anatomic context.

**Comment by fedorov** [comment]
I suggest Segmentation should be augmented to contain the pointer to the "default" terminology context. When a new segment is created, the first "term" from the "default" terminology context should be used.

**Comment by cpinter** [comment]
I like this suggestion too. I was going to store the last selected terminology in the application settings, because I think the user would like to keep using their custom terminology across Slicer sessions.

**Comment by cpinter** [comment]
(We could do a quick 2-minute hangout, so that we can discuss it more efficiently)

**Comment by fedorov** [comment]
> I was going to store the last selected terminology in the application settings

That's a good idea too! Workflows could then change that setting if they want to use application-specific context.

Unfortunately, there is no "standard" way to associate segmentation context with the DICOM Segmentation object, so we would not be able to initialize the default segmentation context for the segmentation node after loading from DICOM, so perhaps your suggestion to store the context to be used in the app settings is more consistent.

**Comment by cpinter** [comment]
Changes committed in
https://github.com/Slicer/Slicer/commit/9613ba223b8074128b56f32746ae653c8c4d9569
Let me know if any of the two changes (see commit message) need tweaking

**Comment by chribaue** [comment]
@fedorov Yes, I think this is helpful for several users and workflows.
