### ISSUE TITLE
Making segmentation in segment editor read-only

### ISSUE THREAD

**Issue by lassoan** [QIICR/QuantitativeReporting#152]
See discussion in https://github.com/QIICR/QuantitativeReporting/issues/143

-------

che85 commented 10 hours ago 
@lassoan I just noticed that it would be great to have a read only mode for the Segment Editor. In case that we want to load a "completed" SR, the user should neither be able to add/remove any segments nor modify any of the segments. Therefore I would suggest to expose to the developers the button(s) or buttongroupbox and the effects parent which could be disabled.
Otherwise another solution would be to implement a readonly mode on side of the Segment Editor. I can imagine that users not always want to enable further editing of segmentations.
Other than that the segments table should always allow selection but not modification of name or terminology.
What do you think?

  
lassoan commented 10 hours ago 
What would you show in read-only mode? Only the segment list?
    

che85 commented 10 hours ago 
Showing the buttons and everything is fine. I would just disable the mentioned components.

che85 commented 10 hours ago 
I would almost go that far and set an attribute for vtkMRMLSegmentationNodes to be readonly.
That's how I am doing it right now in Quantitative Reporting

    
che85 commented 9 hours ago 
It would also be great to either expose the SegmentsTableView to the developer because I am currently setting the readonly for that as follows:
self.segmentEditorWidget.table.setReadOnly(True)
otherwise it could just be implemented with the readonly in the Segment Editor itself so that the developer don't need direct access to SegmentsTableView

**Comment by lassoan** [comment]
@che85

Markups and Table nodes have a "Locked" attribute. If a node is locked then you cannot edit it on the GUI (editors check the value of this attribute and disable editing). The same idea could be applied to Segmentation nodes.

Would you like to prevent users from editing your segmentation in the standard Segment Editor module?
Would you like to prevent users from unlocking your segmentation using the GUI (for markups and tables the user can unlock a node easily)?

**Comment by che85** [comment]
@fedorov What are your thoughts on that? I am no sure. If a user saved a report (not completed) then users should be able to load and continue working on the segmentations. If the SR was completed, a segmentation should be locked and not further modification should be allowed.

**Comment by che85** [comment]
@lassoan I tested with most recent nightly and I noticed one thing:

Assuming I have a segmentation with two segments loaded in the segment editor and running the following code:
```
s = slicer.modules.SegmentEditorWidget
s.editor.setReadOnly(True)
```
After selection of a segment from the table, the SegmentEditor is not anymore readonly.

Other than that an active effect stays activated after setting readonly to True which mustn't be allowed.

**Comment by lassoan** [comment]
Fixed in r25913.

**Comment by lassoan** [comment]
Do you prefer to keep tickets open until they are verified?
We could add a new ticket state (Test) that indicates that the development is completed and the code is ready for testing.

**Comment by che85** [comment]
Works for me! Thanks a lot to @lassoan
