### ISSUE TITLE
DICOM images are not loaded in to QR getting following error

### ISSUE THREAD

**Issue by DharmendraModi** [QIICR/QuantitativeReporting#156]
I want to draw measurements and export SR as TID1500 report.  

I have installed slicer, and enabled Quantitative Reporting. After loading the images the Segmentation is not getting enabled. 

I see following details.
![segmentationdoesnnotenable](https://cloud.githubusercontent.com/assets/27244473/24884331/e501be7e-1e16-11e7-8cdf-8f44a65fd84c.jpg)

Switch to module:  "QuantitativeReporting"
QSqlDatabasePrivate::removeDatabase: connection 'DICOM-DB' is still in use, all
queries will cease to work.
QSqlDatabasePrivate::addDatabase: duplicate connection name 'DICOM-DB', old conn
ection removed.
QSqlDatabasePrivate::removeDatabase: connection 'DICOM-DBTagCache' is still in u
se, all queries will cease to work.
QSqlDatabasePrivate::addDatabase: duplicate connection name 'DICOM-DBTagCache',
old connection removed.
Traceback (most recent call last):
  File "C:\Users\dharmendra.modi\AppData\Roaming\NA-MIC\Extensions-25912\SlicerP
rostate\lib\Slicer-4.7\qt-scripted-modules\SlicerProstateUtils\decorators.py", l
ine 220, in f
    func(*args, **kwargs)
  File "C:/Users/dharmendra.modi/AppData/Roaming/NA-MIC/Extensions-25912/Quantit
ativeReporting/lib/Slicer-4.7/qt-scripted-modules/QuantitativeReporting.py", lin
e 93, in setup
    self.setupSelectionArea()
  File "C:/Users/dharmendra.modi/AppData/Roaming/NA-MIC/Extensions-25912/Quantit
ativeReporting/lib/Slicer-4.7/qt-scripted-modules/QuantitativeReporting.py", lin
e 169, in setupSelectionArea
    self.imageVolumeSelector.addAttribute("vtkMRMLScalarVolumeNode", "DICOM.inst
anceUIDs", None)
AttributeError: 'NoneType' object has no attribute 'addAttribute'

**Comment by che85** [comment]
@DharmendraModi Thanks for reporting. This is related to changes in the SegmentEditor. https://github.com/QIICR/QuantitativeReporting/pull/154 addresses this issue.

**Comment by DharmendraModi** [comment]
Thank you for your help. Please let me know when it is resolved.

**Comment by fedorov** [comment]
The pull request @che85 mentioned has been merged. If you use the module from source, you can checkout the latest version and try again!

**Comment by che85** [comment]
@DharmendraModi If you want, go ahead and install Slicers most recent nightly build. I just tested it and it works fine for me. Therefore closing this issue.

**Comment by DharmendraModi** [comment]
I just downloaded it, I am able to load images, but when I try to save Report. I get error "QuantitativeReportWidget' object has not attribute 'seiresNumber'
![noseriesnumber](https://cloud.githubusercontent.com/assets/27244473/24916832/56a27626-1ea9-11e7-8d4a-b427c705e76d.jpg)

**Comment by DharmendraModi** [comment]
Also the DICOM Heder Sutdy ID and Patient Name still are not being displayed.
![alsostudyid and patientname stay blank](https://cloud.githubusercontent.com/assets/27244473/24917002/cbbec522-1ea9-11e7-8d57-d2de2aa5639c.jpg)

**Comment by che85** [comment]
@DharmendraModi Can you share those datasets or are they confidential?

**Comment by che85** [comment]
@DharmendraModi I created another issue for that (https://github.com/QIICR/QuantitativeReporting/issues/157)

**Comment by DharmendraModi** [comment]
Actually they are confidential, I tried the retrieve test data, but I got bellow error.
I will try another data set.
  
File "C:/Users/dharmendra.modi/AppData/Roaming/NA-MIC/Extensions-25914/Quantit
ativeReporting/lib/Slicer-4.7/qt-scripted-modules/QuantitativeReporting.py", lin
e 134, in loadTestData
    from SEGExporterSelfTest import SEGExporterSelfTestLogic
ImportError: No module named SEGExporterSelfTest

**Comment by che85** [comment]
Ok seems like I invented this bug with the last PR since I removed the SEGExporterSelfTest. I will fix this quickly and get back to you.

**Comment by DharmendraModi** [comment]
Hi Christian,

I still get same error. Since, I couldn't load test data, I loaded another data set, but same error. I can't save report. Please view attached snap.

![savereporterror](https://cloud.githubusercontent.com/assets/27244473/24961713/b2ae3888-1f67-11e7-84d5-6a3d8ab973f8.jpg)

**Comment by che85** [comment]
@DharmendraModi It's not yet merged. I am waiting for @lassoan to comment on my feature request. I will let you know once I know it will be ready.

**Comment by fedorov** [comment]
@DharmendraModi sorry for the troubles. We appreciate your feedback and patience.

**Comment by lassoan** [comment]
`> I am waiting for @lassoan to comment on my feature request. I will let you know once I know it will be ready.`

Just to make sure I haven't missed it - which feature request?

**Comment by che85** [comment]
@lassoan It was more a comment than a feature request. Sorry for the confusion. 

https://github.com/Slicer/Slicer/commit/538f9f1ad9ade8f6f806e1190d9b2e7b17c549e5#diff-7c7eec0c29e48a2151fe45095d3c870fL224

**Comment by fedorov** [comment]
@DharmendraModi this issue is expected to be resolved in the today's Slicer nightly. Can you please let us know if it is working for you, so we can close this issue?

**Comment by DharmendraModi** [comment]
Thank you. I am successfully able to Retrieve test data and save SR.

**Comment by che85** [comment]
@DharmendraModi Happy to hear this! I am closing this issue then.
