### ISSUE TITLE
Patient information are not displayed/updated

### ISSUE THREAD

**Issue by che85** [QIICR/QuantitativeReporting#157]
reported by @DharmendraModi 

> I just downloaded it, I am able to load images, but when I try to save Report. I get error "QuantitativeReportWidget' object has not attribute 'seiresNumber'
> ![noseriesnumber](https://cloud.githubusercontent.com/assets/27244473/24916832/56a27626-1ea9-11e7-8d4a-b427c705e76d.jpg)
> Also the DICOM Heder Sutdy ID and Patient Name still are not being displayed.
> ![alsostudyid and patientname stay blank](https://cloud.githubusercontent.com/assets/27244473/24917002/cbbec522-1ea9-11e7-8d57-d2de2aa5639c.jpg)

**Comment by che85** [comment]
@DharmendraModi Are you using the extension from source of from the ExtensionManager?

**Comment by che85** [comment]
@lassoan I need to observer onMasterVolumeNodeChanged of the SegmentEditorWidget in order to retrieve patient information for a) displaying them in QuantitativeReporting and b) creating the report. You removed the access to it in https://github.com/Slicer/Slicer/commit/538f9f1ad9ade8f6f806e1190d9b2e7b17c549e5

**Comment by DharmendraModi** [comment]
Hi Christian,

I am using Extension Manger, how do I load it from source.

**Comment by che85** [comment]
@DharmendraModi 

1. Download  and unzip https://github.com/QIICR/QuantitativeReporting/archive/master.zip
2. Go to your Slicer Application Settings
![image](https://cloud.githubusercontent.com/assets/10195822/24921226/18f89c92-1eb8-11e7-8c95-f4fd9a80385b.png)
3. Go to `Modules`
![image](https://cloud.githubusercontent.com/assets/10195822/24921246/2fa5cf3c-1eb8-11e7-8f0c-c9ad91585dd8.png)
4. If you installed QuantitativeReporting from the ExtensionManager select the paths as shown in the screenshot and push `Remove`
![image](https://cloud.githubusercontent.com/assets/10195822/24921323/6cf0a218-1eb8-11e7-9c69-bd24951319f0.png)
5. Push `Add` and select {unzippedDirectory}
6. Push `Add` a **second time** and select {unzippedDirectory}/DICOMPlugins

**Comment by che85** [comment]
@DharmendraModi but still it wouldn't help you right now because QuantitativeReporting depends on the SegmentEditor where changes (if made) will be available in the next nightly build of Slicer once committed/merged.

**Comment by DharmendraModi** [comment]
Thank you for all your help. Really Appreciated. I will try tomorrow.

**Comment by che85** [comment]
@DharmendraModi Everything should be working in the next nightly build coming up. Thanks for your patience and especially for reporting it to us!
