### ISSUE TITLE
Slicer could not find SlicerDevelopmentToolbox, DCMQI

### ISSUE THREAD

**Issue by johnflavin** [QIICR/QuantitativeReporting#164]
I'm installing the Quantitative Reporting Slicer extension following the tutorial video http://qiicr.org/dcmqi-guide/tutorials/intro.html. I have installed Slicer not from the website, but using Homebrew Cask (`$ brew cask install slicer`). I have version 4.6.2. 

When I open Slicer and install the Quantitative Reporting extension, it gives me an error message:
<img width="532" alt="screen shot 2017-06-08 at 8 39 57 am" src="https://user-images.githubusercontent.com/1417503/26931597-a65fb8b8-4c26-11e7-89ac-6ab487aba51d.png">
> QuantitativeReporting depends on the following extensions, which could not be found:
> * SlicerDevelopmentToolbox
> * DCMQI
>
> The extension may not function properly

When I search for the dcmqi extension, I find no results.
> No extensions found for macosx:64-bit, revision: '25516'. Please try a different combination

**Comment by fedorov** [comment]
John, you will need to install 4.7 - the extension requires the nightly version of Slicer. The "stable" is close to 1 year old and cannot be updated. If you just follow the install instructions and install it from the nightly binary as shown in the instructions, that should work.

**Comment by johnflavin** [comment]
Ok, thanks. I'll get the nightly build.
