### ISSUE TITLE
Initiallize quantitative report with an existing segmentation

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#173]
It will be helpful if an existing segmentation could be attached (imported?) into a new quantitative report. It can be limiting to only be able to create segmentation from within the QR UI.

**Comment by che85** [comment]
You are talking about a DICOM segmentation, right? Then we would have to make sure that the referenced source image has the same instance UID as the currently processed master volume

**Comment by fedorov** [comment]
Or if not - notify the user and prompt to resample to the master volume.

**Comment by che85** [comment]
@lassoan is there a way to get the following components from outside of the Segmentations module? 
![image](https://user-images.githubusercontent.com/10195822/29188246-83065980-7de0-11e7-822c-0a9bc11c9162.png)

In QuantitativeReporting we would like to add the following functionality:
* import labelmap into current segmentation
* copy segments from other segmentations to current segmentation

The mentioned widget provides that functionality but I was not able to find easy access to it. Maybe you have some ideas or pointers that would simplify this process?

**Comment by lassoan** [comment]
The logic behind these widgets (that do the actual copying/moving/exporting/importing) is accessible from another module, as it is implemented in vtkSlicerSegmentationsModuleLogic or in vtkMRMLSegmentationNode.

The copying/moving/exporting/importing section widgets are part of qSlicerSegmentationsModuleWidget, so they are currently not accessible as standalone, reusable widgets. Our assumption was that if you want to import/export data in your custom module then you would use a custom, optimized, simplified user interface.
