### ISSUE TITLE
Add button to disable surface smoothing and update the surface

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#176]
See discussion here: https://discourse.slicer.org/t/option-to-disable-smoothing-of-the-segment-surfaces-in-segment-editor/883/15

I think it will be helpful to add a shortcut to the module that would set smoothing parameter to 0 and update the surface, since smoothing significantly under-estimates the volume. It is especially prominent for even medium-sized structures in the QIN-HEADNECK dataset.

**Comment by cpinter** [comment]
This PR will address this issue
https://github.com/Slicer/Slicer/pull/783

**Comment by lassoan** [comment]
Manual adjustment of smoothing parameters may be a good short-term solution, but a better approach could be to compute volume from the master representation and/or tune smoothing to take into account the labelmap voxel size.

**Comment by cpinter** [comment]
Added smoothing parameter controls in Segment Editor widget as action of Show 3D button
https://github.com/Slicer/Slicer/commit/36fe64b16734c962156c5f574280a6fa7b9cccb6
