### ISSUE TITLE
Anatomic Region Modifier is not displayed in terminology tooltip

### ISSUE THREAD

**Issue by che85** [QIICR/QuantitativeReporting#199]
If available, the Anatomic Region Modifier should be displayed.

![image](https://user-images.githubusercontent.com/10195822/30832496-40d94cc2-a219-11e7-9df3-10cc1286396a.png)

![image](https://user-images.githubusercontent.com/10195822/30832707-15fd80d0-a21a-11e7-919b-99e93da3508a.png)

**Comment by che85** [comment]
@cpinter I just downloaded the most recent nightly build and noticed that this issue still has not been resolved. Here some hints.

I created a segmentation, stored it into DICOM and loaded it back into Slicer. The following shows the terminology information 

### a) Segment Editor
![image](https://user-images.githubusercontent.com/10195822/34585681-c1b01ba6-f16e-11e7-9c37-1a4c8268c1ba.png)

### b) Terminology popup
![image](https://user-images.githubusercontent.com/10195822/34585710-e20a126c-f16e-11e7-85d5-84a4869e579c.png)

### c) Data module
![image](https://user-images.githubusercontent.com/10195822/34585693-cba71e2a-f16e-11e7-9606-cb6f40af7b55.png)

a) and b) show no anatomic region modifier, but c) does

The following screenshots show the terminology information displayed for the newly created segmentation:

### a) Segment Editor
![image](https://user-images.githubusercontent.com/10195822/34585637-97beebd8-f16e-11e7-91d1-304bb19d49b3.png)

### b) Terminology popup
![image](https://user-images.githubusercontent.com/10195822/34585779-385bcbb0-f16f-11e7-90f2-2225365cc6eb.png)

### c) Data module
![image](https://user-images.githubusercontent.com/10195822/34585629-8cb3d640-f16e-11e7-94dc-88818fcc609c.png)

a) and b) show anatomic region modifier, but c) does not

**Comment by che85** [comment]
@fedorov Maybe this could be another goal for the project week?

**Comment by fedorov** [comment]
Yes, hopefully something quick to fix

**Comment by cpinter** [comment]
So sorry guys, I somehow missed this. Not intentional I promise :) Should be easy to fix, I'll look into this asap.

**Comment by cpinter** [comment]
I could confirm the issue. It seems that the exported context didn't save the modifiers (see your b) screenshot) and that's why it's not recognized. I'll try to find out why this happens.

**Comment by cpinter** [comment]
Fixed in https://github.com/Slicer/Slicer/commit/42566788b1229bebaae7ad2eff68fe8a20f87a51

The issue was not at saving but loading: the anatomic region modified json object was not initialized, and it even crashed in debug mode. I think this was a case for which we didn't have test data (or scenario) at that point. so that part of the code was never executed.

**Comment by fedorov** [comment]
Thank you Csaba!

**Comment by che85** [comment]
Tested and works. Thanks Csaba!
