### ISSUE TITLE
BUG: Referenced scalar volume not loaded when loading SR/SEG into Slicer

### ISSUE THREAD

**Issue by che85** [QIICR/QuantitativeReporting#205]
caused by 
https://github.com/Slicer/Slicer/commit/fce63b47161baecc320672e93b879c0e08d3ed9a#diff-72abf59758d07b4b52e73040fc7f4565R684

**Comment by fedorov** [comment]
> caused by Slicer/Slicer@fce63b4#diff-72abf59758d07b4b52e73040fc7f4565R684

cc: @cpinter

**Comment by che85** [comment]
Will be fixed by https://github.com/Slicer/Slicer/pull/844
