### ISSUE TITLE
Link to home page is wrong in Extension Manager page

### ISSUE THREAD

**Issue by michaelschwier** [QIICR/QuantitativeReporting#211]
When viewing the QuantitativeReporting Extension in Slicer's Extension Manager, the link to the homepage leads to an empty page. Correct would be this one I guess: https://www.slicer.org/wiki/Documentation/Nightly/Extensions/QuantitativeReporting

Would it also be possible to add a link there that leads directly to the User Guide: https://qiicr.gitbooks.io/quantitativereporting-guide/

**Comment by fedorov** [comment]
Thanks! I think the second link is all we need. I will fix it.
