### ISSUE TITLE
Measurements SR are not handled as read only

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#215]
It seems that going out of QR and back modifies the table with the measurements loaded from DICOM SR, which is expected to be constant.

**Comment by che85** [comment]
@fedorov I was not able to reproduce this issue. Nonetheless I changed some behavior in https://github.com/che85/Reporting/commit/388bfed0dd8d7c408e84d958461a2624e7eb889c where the measurement table is not anymore set to None on exitting the module.
