### ISSUE TITLE
Update revision has in ExtensionsIndex 4.8 branch

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#224]
It is currently pointing to master. Need to change to the release that is working for 4.8, and also for the dependencies.

@che85 can you also do it for SlicerProstate?

**Comment by che85** [comment]
@fedorov I hope I didn't miss anything. The only module I didn't update is http://www.github.com/SlicerProstate/SlicerProstate

**Comment by fedorov** [comment]
Thank you, I will update SlicerProstate - there were no changes since 4.8 release, so I just made a tag.

**Comment by lassoan** [comment]
Note that if you create a 4.8 tag instead of a 4.8 branch then you make it very difficult for yourself to deliver patches for 4.8 (independently from development on the master branch).

**Comment by fedorov** [comment]
Great point Andras, I missed that. Thank you, I will make a branch.

**Comment by fedorov** [comment]
done
