### ISSUE TITLE
'module' object has no attribute 'itkimage2segimage' when click 'Save Report' button

### ISSUE THREAD

**Issue by RitchieAlpha** [QIICR/QuantitativeReporting#230]
I use the software '3D Slicer 4.8.1' on mac. When I want to save the report. the software warns me that 'module' object has no attribute     'itkimage2segimage' , it indeed confused me, I wish you can help me!
Thank you!

**Comment by fedorov** [comment]
Thanks for your feedback!

This module depends on [dcmqi](https://github.com/qiicr/dcmqi). The error seems to indicate that the dcmqi extension has not been installed.

How did you install the extension - manually from a local build, or using the ExtensionManager? If you used Extension Manager, the dcmqi dependency should have been installed automatically.

**Comment by RitchieAlpha** [comment]
it worked
Thank you!
