### ISSUE TITLE
Associate 3d-slicer-extension topic with the repository

### ISSUE THREAD

**Issue by jcfr** [QIICR/QuantitativeReporting#237]
Could you associate the `3d-slicer-extension` GitHub topic so that it is listed here: https://github.com/topics/3d-slicer-extension

To learn more about topic, read https://help.github.com/en/articles/about-topics

**Comment by fedorov** [comment]
It's already there: 
![image](https://user-images.githubusercontent.com/313942/55905597-56c29b00-5ba0-11e9-929b-cc9a37c106c4.png)

Or did you add it after submitting the issue?

**Comment by jcfr** [comment]
Ooops, I missed it.
