### ISSUE TITLE
Segment name is not stored in exported segmentation object

### ISSUE THREAD

**Issue by lassoan** [QIICR/QuantitativeReporting#251]
I’m helping Dr Simpson with developing script for converting mhd files to DICOM segmentation objects for uploading to TCIA. The script uses Slicer QuantitativeReporting extension and it works nicely, it creates valid DICOM files that can be imported and loaded successfully.

However, I noticed that after a roundtrip DICOM export/import, the segment names are changed. For example, from the original “Liver”, “Mass”, “Vein” to “Anatomical structure", “Morphologically altered structure", “Tissue".

I’ve checked the code and it seems that “SegmentLabel” DICOM tag is set from segmentation property type, and “SegmentDescription” DICOM tag is set from segmentation property category. Segment name that is set in Slicer is not stored anywhere.

I would expect that segment name (that the user can specify in Slicer in addition to the standard terminology) would be stored in either SegmentLabel or SegmentDescription field. Property category and type are stored in terminology fields anyway, so we would not lose anything by not storing them in SegmentLabel and SegmentDescription.

Could we change the DICOM segmentation exporter in QuantitativeReporting extension to save segment name in SegmentLabel or SegmentDescription DICOM fields? I can implement is and send a pull request, just want to make sure that this is the right thing to do.

**Comment by fedorov** [comment]
@lassoan yes, this fix makes sense. I think most users do conversion using dcmqi directly, and that is why no one noticed this earlier. Pull request is most welcomed!

Can you share dcmqi configuration parameters as passed by QuantitativeReporting for this case, and a representative subset of data before sending to TCIA? I assume this is the dataset from the Decathlon challenge?
