### ISSUE TITLE
Selection of color for a segment

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#78]
Currently, Terminology widget is used both for controlling color and terminology selection. It is also a bit confusing that user needs to click the color swatch in the column labeled "Color" to change both color and terminology.

How about the following:
- have separate columns for terminology and color, or have a button for color, and another one for terminology for each segment
- when terminology is selected manually, or assigned the default value, color is populated from terminology context
- if user wants to change the default/automatically assigned color, they can click just the color button, and use standard color selector widget

Current behavior of the Terminology widget is a bit confusing, since everything in it should be static, including color selector. Color selector should be non-static in the to-be-developed Terminology editor module.

I am afraid this may not be sufficiently clear.... Thoughts?

**Comment by che85** [comment]
@fedorov What's the status of this issue? I think changing the behavior the way it's implemented now should be fine.

**Comment by fedorov** [comment]
The Segmentations team didn't think this was confusing, so let's leave as is, until someone complains.
