### ISSUE TITLE
Handling multiple master volumes per segmentation

### ISSUE THREAD

**Issue by che85** [QIICR/QuantitativeReporting#80]
I am wondering how we are going to handle multiple volumes when creating the label statistics. Would I have to iterate though all master volumes and combine the results?

Right now we are creating a temporary labelmap in order to calculate label statistics which also expects a volume next to the labelmap as an input.

**Comment by fedorov** [comment]
For the foreseeable future, lets make sure the workflow is constrained so that it is impossible to have multiple master volumes.

**Comment by lassoan** [comment]
I think the behavior of the current Label Statistics module is good: you select a segmentation and optionally also a volume. There are no constraints: you can use the same segmentation with different volumes; and volume is optional (e.g., if you are only interested in segment volumes then you don't need to specify a grayscale volume).

**Comment by che85** [comment]
@lassoan Which Label Statistics module do you mean? I only know the one where you can select a volume and a labelmap. Both need to be selected.

**Comment by pieper** [comment]
I think it is well defined, at least it maps correctly to the DICOM
objects.  A segmentation can be reference on or more source images.  A
quantitative measure, like mean value in a segment can reference the source
segmentation and the image data used to perform the calculation.  We need
to make sure Slicer keeps track of those references so we can correctly
encode the results.  In other words I think there's only one source volume
for the statistics even if the segmentation is based on multiple masters.

**Comment by fedorov** [comment]
I am not questioning whether it is good or bad, right or wrong. All I am saying we should not focus on handling multiple masters in the current development of Reporting, and constrain the scope of features to keep the work manageable. This is why we should make sure it is not possible to have multiple masters in the workflow currently being implemented in Reporting.

**Comment by lassoan** [comment]
Note that you can use qMRMLSegmentEditorWidget's masterVolumeNodeSelectorVisible property to hide the master volume node selector. This way your module that embeds the segment editor widget has full control over what master volume is used.

**Comment by fedorov** [comment]
Excellent, @che85 definitely let's use that feature!

**Comment by che85** [comment]
We are already using that feature. 

@lassoan was talking about a Label Statistics module, where you don't need to define a grayscale volume. Which LabelStatistics module is that? I only know the one where you need to select both in order to get results.

**Comment by lassoan** [comment]
Current LabelStatistics module may require a grayscale volume, but actually it's not necessary. If a grayscale volume is not specified then the labelmap volume can be used as both input and mask in vtkImageAccumulate (and then min, max, mean, stdev columns should be removed or values set to N/A or 0).

**Comment by che85** [comment]
@fedorov Are we still planning to implement the option of having multiple master volumes?

**Comment by fedorov** [comment]
no, not in the foreseeable future ...
