### ISSUE TITLE
Update Reporting-related entries in Slicer DICOM plugin "advisor"

### ISSUE THREAD

**Issue by fedorov** [QIICR/QuantitativeReporting#93]
if/when https://github.com/Slicer/Slicer/pull/504 is merged AND when this module is functional

**Comment by pieper** [comment]
I didn't update the json file because I wasn't sure of the current
suggestions in terms of extensions to install for a given DICOM
modalities.  Let me know if changes need to be made.

https://github.com/Slicer/Slicer/blob/master/Modules/Scripted/DICOM/DICOMExtensions.json

**Comment by fedorov** [comment]
That's ok, I don't think we are quite there yet. I will update later. Thank you!

**Comment by fedorov** [comment]
addressed in https://github.com/Slicer/Slicer/pull/629

**Comment by fedorov** [comment]
Steve, I submitted a PR, let me know if anything needs to be fixed. Not urgent.

**Comment by fedorov** [comment]
advisor PR integrated
